spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/practica_db
spring.datasource.username=usuario_api
spring.datasource.password=password123

# IMPORTANTE: Flyway gestiona, Hibernate solo valida
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true